In [20]:
import os, shutil
import torch
from torch.utils.data import Dataset, SubsetRandomSampler, DataLoader
import numpy as np
import gin
import h5py
from  scipy import signal

ModuleNotFoundError: No module named 'torch'

In [11]:
filename = 'scsn_ps_2000_2017_shuf.hdf5'
url = 'https://service.scedc.caltech.edu/ftp/ross_etal_2018_bssa/scsn_ps_2000_2017_shuf.hdf5'

In [14]:
filename_try = os.path.join(filename, '{}.h5'.format(url))

In [21]:
with h5py.File(filename, 'r') as f:
    print("keys", f.keys())
    a_group_key = list(f.keys())[0]
    y_key = list(f.keys())[1]
    print(f[y_key][1])
    
    
    

    print("dataset shape: ", f[a_group_key], "\n")
    
    data = f[a_group_key][4773749]
    print("count: ", len(data), "\n")
    print("each earthquake looks like this: \n\n", data)
    
    x = f['X']
    y = f['Y']
    print(x)
    print(y)
    

keys <KeysViewHDF5 ['X', 'Y']>
1
dataset shape:  <HDF5 dataset "X": shape (4773750, 400, 3), type "<f4"> 

count:  400 

each earthquake looks like this: 

 [[-0.46408787  0.05357399 -0.39055282]
 [-0.44251317  0.05935051 -0.6741384 ]
 [-0.38108483  0.15430647 -0.59989095]
 ...
 [ 0.05535169 -0.18867616 -0.37687668]
 [-0.02502383 -0.13982143 -0.22604646]
 [-0.10619047 -0.1663093  -0.03767657]]
<HDF5 dataset "X": shape (4773750, 400, 3), type "<f4">
<HDF5 dataset "Y": shape (4773750,), type "|u1">
